---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-cm
  labels:
    app: codeserver
    name: cs-cm  
    
data:
  PUID: "1000"
  PGID: "1000"
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pvc-cm
  namespace: cs
data:
  hosts: |
    127.0.0.1       localhost
    255.255.255.255 broadcasthost
    ::1             localhost
  readme.txt: |
    this is a readme file

    