---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  labels:
    app: codeserver
  namespace: cs    
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-xfs      
  accessModes: [ "ReadWriteOnce" ]
  
