---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: bggapp-po
  template:
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
  namespace: bggns
spec:
  type: LoadBalancer
  selector:
    name: bggapp-po
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ing
  labels:
    name: app-ings
spec:
  ingressClassName: nginx
  rules:
  - host: app-146.190.202.91.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: bggapp-svc
            port: 
              number: 3000